version: 1
services:
  - type: web
    name: aurore-dev  # Nom descriptif pour ton service
    env: php
    plan: free
    buildCommand: "composer install"
    startCommand: "php -S 0.0.0.0:10000 -t public"  # Modifie selon la structure de ton projet
    routes:
      - type: http
        name: web
        path: /
        service: aurore-dev  # Utilise le même nom que ci-dessus